//
// Generated file, do not edit! Created by opp_msgtool 6.2 from msg/AlarmMsg.msg.
//

#ifndef __FORESTFIRESIM_ALARMMSG_M_H
#define __FORESTFIRESIM_ALARMMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace forestfiresim {

class AlarmMsg;

}  // namespace forestfiresim


namespace forestfiresim {

/**
 * Class generated from <tt>msg/AlarmMsg.msg:8</tt> by opp_msgtool.
 * <pre>
 * // AlarmMsg: alarm packet sent by a sensor when it detects (or falsely detects) a fire.
 * // fireEventTimestamp is set by SensorApp at the moment the fire notification arrives,
 * // so that FireServer can compute D_alarm = simTime() - fireEventTimestamp (end-to-end
 * // alarm delay from fire occurrence to reception at the monitoring server).
 * message AlarmMsg
 * {
 *     int sensorId;
 *     double timestamp;           // time the alarm packet was created at the sensor
 *     double fireEventTimestamp;  // time the fire ignition event occurred (for D_alarm)
 *     double sensorReading;
 *     bool isFire;
 *     bool isFalseAlarm;
 *     int zoneId;
 * }
 * </pre>
 */
class AlarmMsg : public ::omnetpp::cMessage
{
  protected:
    int sensorId = 0;
    double timestamp = 0;
    double fireEventTimestamp = 0;
    double sensorReading = 0;
    bool isFire_ = false;
    bool isFalseAlarm_ = false;
    int zoneId = 0;

  private:
    void copy(const AlarmMsg& other);

  protected:
    bool operator==(const AlarmMsg&) = delete;

  public:
    AlarmMsg(const char *name=nullptr, short kind=0);
    AlarmMsg(const AlarmMsg& other);
    virtual ~AlarmMsg();
    AlarmMsg& operator=(const AlarmMsg& other);
    virtual AlarmMsg *dup() const override {return new AlarmMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSensorId() const;
    virtual void setSensorId(int sensorId);

    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);

    virtual double getFireEventTimestamp() const;
    virtual void setFireEventTimestamp(double fireEventTimestamp);

    virtual double getSensorReading() const;
    virtual void setSensorReading(double sensorReading);

    virtual bool isFire() const;
    virtual void setIsFire(bool isFire);

    virtual bool isFalseAlarm() const;
    virtual void setIsFalseAlarm(bool isFalseAlarm);

    virtual int getZoneId() const;
    virtual void setZoneId(int zoneId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlarmMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlarmMsg& obj) {obj.parsimUnpack(b);}


}  // namespace forestfiresim


namespace omnetpp {

template<> inline forestfiresim::AlarmMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<forestfiresim::AlarmMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FORESTFIRESIM_ALARMMSG_M_H

