//
// Generated file, do not edit! Created by opp_msgtool 6.2 from msg/TelemetryMsg.msg.
//

#ifndef __FORESTFIRESIM_TELEMETRYMSG_M_H
#define __FORESTFIRESIM_TELEMETRYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace forestfiresim {

class TelemetryMsg;

}  // namespace forestfiresim


namespace forestfiresim {

/**
 * Class generated from <tt>msg/TelemetryMsg.msg:4</tt> by opp_msgtool.
 * <pre>
 * message TelemetryMsg
 * {
 *     int sensorId;
 *     double timestamp;
 *     double temperature;
 *     double humidity;
 *     double smokeLevel;
 *     double windSpeed;
 *     bool nearThreshold;
 * }
 * </pre>
 */
class TelemetryMsg : public ::omnetpp::cMessage
{
  protected:
    int sensorId = 0;
    double timestamp = 0;
    double temperature = 0;
    double humidity = 0;
    double smokeLevel = 0;
    double windSpeed = 0;
    bool nearThreshold = false;

  private:
    void copy(const TelemetryMsg& other);

  protected:
    bool operator==(const TelemetryMsg&) = delete;

  public:
    TelemetryMsg(const char *name=nullptr, short kind=0);
    TelemetryMsg(const TelemetryMsg& other);
    virtual ~TelemetryMsg();
    TelemetryMsg& operator=(const TelemetryMsg& other);
    virtual TelemetryMsg *dup() const override {return new TelemetryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSensorId() const;
    virtual void setSensorId(int sensorId);

    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);

    virtual double getTemperature() const;
    virtual void setTemperature(double temperature);

    virtual double getHumidity() const;
    virtual void setHumidity(double humidity);

    virtual double getSmokeLevel() const;
    virtual void setSmokeLevel(double smokeLevel);

    virtual double getWindSpeed() const;
    virtual void setWindSpeed(double windSpeed);

    virtual bool getNearThreshold() const;
    virtual void setNearThreshold(bool nearThreshold);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TelemetryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TelemetryMsg& obj) {obj.parsimUnpack(b);}


}  // namespace forestfiresim


namespace omnetpp {

template<> inline forestfiresim::TelemetryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<forestfiresim::TelemetryMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FORESTFIRESIM_TELEMETRYMSG_M_H

